### ISSUE TITLE
Create multiple pre-truncated id outputs automatically

### ISSUE THREAD

**Issue by alexjurkiewicz** [cloudposse/terraform-null-label#117]
I am happy to implement this feature. I wanted to see if it would be supported first though 😊 

## Describe the Feature

Add outputs `id_16`, `id_32`, `id_64`, `id_128`.

## Expected Behavior

They would act like `id` output with differing `id_length_limit` values set.

## Use Case

It's often the case I want to use the same label for different resources with different name restrictions. For example, using the label to name a RDS cluster (no limit) and to name_prefix an IAM Role (32char limit).

At the moment, I have to set the `id_length_limit` value to the smallest required by all resources, which can result in names that are needlessly terse for 99% of resources.

## Describe Ideal Solution

Next minor release (add new outputs only):

* Add `id_16`, `id_32`, `id_64`, `id_128`, etc as above

Next major release (require use of new outputs):

* `id`, `id_length_limit` are removed
* Users use `id_N` or `id_full` to get the correct length ID

## Alternatives Considered

The major release idea can be dropped. I like the idea of making users be explicit around their length, since most resources do have _some_ length restriction.

**Comment by osterman** [comment]
This is an interesting proposal. Definitely open to it as an _alternative_ to using `id_length_limit`.

cc: @Nuru

**Comment by Nuru** [comment]
@osterman While I can get behind the idea of multiple length limits, I would not want those length limits to be pre-defined or individually output, both on general principles and because of the excessive documentation it produces. 

A better design, IMHO, is to replace or augment `id_length_limit` with `id_length_limits` list of numbers and output a map of `lengths = ids`. For example 

```
id_length_limits = [16, 32, 64]
```
Yields `id_max_len[16], id_max_len[32], and id_max_len[64]`

**Comment by Nuru** [comment]
Closing as `wontfix`, see discussion at #118 for why.
