### ISSUE TITLE
A reference to "each.value" has been used in a context in which it unavailable

### ISSUE THREAD

**Issue by fitchtech** [cloudposse/terraform-null-label#127]
https://github.com/cloudposse/terraform-null-label/blob/cf38625a5dde227db04c9cfedc1327d610229fec/examples/autoscalinggroup/main.tf#L27-L32

  tag_specifications {
    for_each = ["instance", "volume", "elastic-gpu", "spot-instance-request"]

    resource_type = each.value
    tags          = module.label.tags
  }

Error: each.value cannot be used in this context

  on launchtemplate.tf line 68, in resource "aws_launch_template" "default":
  68:     resource_type = each.value

A reference to "each.value" has been used in a context in which it
unavailable, such as when the configuration no longer contains the value in
its "for_each" expression. Remove this reference to each.value in your
configuration to work around this error.

cfitch@8J98693:~/fitch-eks$ terraform plan

Error: each.value cannot be used in this context

  on launchtemplate.tf line 68, in resource "aws_launch_template" "default":
  68:     resource_type = each.value

A reference to "each.value" has been used in a context in which it
unavailable, such as when the configuration no longer contains the value in
its "for_each" expression. Remove this reference to each.value in your
configuration to work around this error.

**Comment by Nuru** [comment]
@fitchtech I am closing this as "not-a-bug" but am open to re-opening it if you provide more information and show that it really is an issue we can and should fix.

First, the error message refers to `launchtemplate.tf line 68`. We have no `launchtemplate.tf` so I don't know what we should change or where.

Second, the error message is a Terraform issue about changing an existing configuration. It appears to be related to [this issue](https://github.com/hashicorp/terraform/issues/26146) which was present in Terraform 0.13.2 but fixed in Terraform 0.13.3.

**Comment by Nuru** [comment]
@fitchtech I am closing this as "not-a-bug" but am open to re-opening it if you provide more information and show that it really is an issue we can and should fix.

First, the error message refers to `launchtemplate.tf line 68`. We have no `launchtemplate.tf` so I don't know what we should change or where.

Second, the error message is a Terraform issue about changing an existing configuration. It appears to be related to [this issue](https://github.com/hashicorp/terraform/issues/26146) which was present in Terraform 0.13.2 but fixed in Terraform 0.13.3.
