### ISSUE TITLE
Feature request: support renaming/dropping default tags

### ISSUE THREAD

**Issue by alexjurkiewicz** [cloudposse/terraform-null-label#128]
## Describe the Feature

Allow changing the name of default tags, or dropping them entirely.

## Expected Behavior

1. Ability to rename default tags, eg rename `Stage` to `environment`
2. Ability to remove default tags, eg prevent `namespace` tag from being created

## Use Case

We use this module a lot, but some of the tag names don't match our internal standard. For example, we use "environment" rather than "stage". As a workaround, we set additional_tag_map = { environment = "dev" }, but this means we have a Stage tag which duplicates the value.

In AWS this is a problem since there is a limit of 10 tags per resource, and we add other tags globally for cost /security control.

## Describe Ideal Solution

```terraform
module "context" {
  ...
  stage_tag_name = "environment" # use 'environment' instead of 'stage'
  namespace_tag_name = "" # don't create a namespace tag at all
}
```

## Additional Context

I suggested this idea in the CloudPosse slack, some feedback exists there: https://sweetops.slack.com/archives/CB6GHNLG0/p1621557927034000

**Comment by ricbartm** [comment]
I share the same problem/concern as Alex. We find this very opinionated and not aligned with our tagging strategy

**Comment by Nuru** [comment]
It is true, as @ricbartm said, this module is opinionated: it reflects Cloud Posse's opinion about providing a consistent naming and tagging system. However, it is not as bad as @alexjurkiewicz seems to think.

It is not exactly clear what results @alexjurkiewicz wants, because this module does require all generated tag keys to have the same letter case pattern, either UPPER, lower, or Title. The proposal wants to replace `Stage` with `environment`. You can set `label_key_case = "lower"` to get all the tag keys to be all lower case, but, yes, our opinion is that they should all be formatted the same way, so this module does not provide the ability to keep the `name` tag as "Name" while having the `environment` tag as "environment', you either get "Name" and "Environment" or "name" and "environment".  We are not going to change that.

Otherwise, the changes @alexjurkiewicz wants are already available via the `label_order` variable. Setting 
```hcl
label_order = ["environment", "name", "attributes"]
```
will prevent the `namespace` and `stage` tags from being created (and prevent `namespace` and `stage` from appearing in the generated IDs) and will use the `environment` variable as the value of the tag named `Environment`. 

It seems the customizations available via `label_order` and `label_key_case` are sufficient to handle enough use cases that I am reluctant to offer further customizations. @alexjurkiewicz If you agree they address your use case, please close this issue. If you disagree, please explain further why they are not enough for you.

**Comment by alexjurkiewicz** [comment]
Since opening this, we decided to migrate to AWS provider default_tags. Thanks for explaining the workarounds though! They are not very intuitive, but it's nice to know some customisation is possible.

**Comment by osterman** [comment]
Also, a couple of other notes:
- In this particular case, we already support `environment` and all parameters are optional, so if `stage` is not desirable, omit it and use `environment` instead (I realize this was just an example and get your point)
- With the `context.tf` pattern, any additional `tags` can be passed very easily through to all modules with more granular control than with the provider's default tags

**Comment by osterman** [comment]
@ricbartm can you provide an example of your tagging strategy?
