### ISSUE TITLE
Valid resource characters are being replaced by null label module.

### ISSUE THREAD

**Issue by perplexa** [cloudposse/terraform-null-label#147]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Valid resource character `/` is being replaced in ECR's `name` variable.

## Expected Behavior
Valid resource character `/` is not being replaced in ECR's `name` variable.

## Steps to Reproduce
1. Use `tfr:///cloudposse/ecr/aws//.?version=0.38.0` terraform module
2. Set name `a/b`
3. Name becomes `ab`

Edit: I added `/` manually to regex_replace_chars for the time being but it would be nice to change the default to include slashes. :)

**Comment by Nuru** [comment]
Different resources have different naming restrictions. For example, [S3 Bucket names](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) can consist only of lowercase letters, numbers, dots (.), and hyphens (-). The default naming convention used by `null-label` is the most restrictive, so that it works for all AWS resources. If you don't like the default, you can easily modify the rules, as you discovered. 

Changing the default risks massively impacting existing infrastructure and would _require_ overriding the default in some use cases to avoid creating invalid resource names, which would cause Terraform to fail to create the resource. I am rejecting this PR to preserve the current behavior where `null-label` generates widely compatible AWS resource names and users and optionally modify inputs to generate richer, resource-specific names when desired.
