### ISSUE TITLE
Is the null provider still required?

### ISSUE THREAD

**Issue by lae** [cloudposse/terraform-null-label#82]
I'm only starting to use this module, but I noticed the latest release and #80 and so thought to remove the null provider from `versions.tf` and it looks like it still works?

edit:
Specifically, the change at https://github.com/fressets/terraform-null-label/pull/1. So far have only been using it for simple labels (as well as the context feature) for labeling DigitalOcean instances and volumes and not much else (but I think that covers most of this module?). And if it isn't needed, then there's the question about the module name not being apt anymore (for 0.12 at least), I guess?

**Comment by sheldonhull** [comment]
@maartenvanderhoef  @aknysh @osterman 

I'm getting failures due to the removal of this resource right now. 

```
Error: Provider configuration not present

To work with
module.service_account.module.label.data.null_data_source.tags_as_list_of_maps[0]
its original provider configuration at
provider["registry.terraform.io/-/null"] is required, but it has been removed.
This occurs when a provider configuration is removed while objects created by
that provider still exist in the state. Re-add the provider configuration to
destroy
module.service_account.module.label.data.null_data_source.tags_as_list_of_maps[0],
after which you can remove the provider configuration again.
```

Any tips on resolving this migration issue? I'm in the middle of 0.13upgrade on a few modules and this is blocking the plan from running right now. Not sure if I can leverage the `replace-provider` command like the docs show, but hoping you might have a fix already if you ran into this.

https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations

**Comment by osterman** [comment]
We haven't yet tackled 0.13 - so don't know the answer. Will accept PRs that fix it.

**Comment by sheldonhull** [comment]
@osterman I'm referring to 0.17 release, this was supposed to support 0.13 terraform version.
I think it's actually the removal of the tags_as_list_of_maps from 0.16 release, just not sure how to properly migrate this.

**Comment by osterman** [comment]
this looks like the same class of problem that's here: https://github.com/cloudposse/terraform-aws-eks-cluster/issues/58

It's due to terraform not handling certain kinds of deprecations of resources and module upgrades at the same time. 

The fix is probably to `terraform rm module.service_account.module.label.data.null_data_source.tags_as_list_of_maps[0]` and try again. 

See the discussion in the other issue.
